services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./html:/srv:ro
      - caddy_data:/data
      - caddy_config:/config

    security_opt:
      - no-new-privileges:true

    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    expose:
      - "5000"

volumes:
  caddy_data:
  caddy_config:

